package com.example.axmovies.model

data class Movie(
    var year: String? = "",
    val adult: Boolean,
    var backdrop_path: String? = null,
    val belongs_to_collection: Any,
    val budget: Int,
    val genreIds: List<Int> = listOf(),
    var genres: String? = "",
    val homepage: String,
    val id: Int,
    val imdb_id: String,
    val original_language: String,
    val original_title: String,
    val overview: String,
    val popularity: Double,
    var poster_path: String? = null,
    val production_companies: List<ProductionCompany>,
    val production_countries: List<ProductionCountry>,
    val release_date: String,
    val revenue: Int,
    val runtime: Int,
    val spoken_languages: List<SpokenLanguage>,
    val status: String,
    val tagline: String,
    val title: String,
    val video: Boolean,
    val vote_average: Double,
    val vote_count: Int
)